mod amnesomrade;
mod base;
mod etymologi;
mod hv;
mod idiom;
mod lexem;
mod morfex;
pub mod saol_lemma;
mod sentens;
mod so_base;
pub mod so_lemma;
pub mod superlemma;
mod syntex;
mod uttal;
mod valens;

pub use amnesomrade::Ämnesområde;
pub use base::Status;
pub use etymologi::Etymologi;
pub use hv::{Hv, HänvisningsTyp};
pub use idiom::{Idiom, IdiomBetydelse};
pub use lexem::SoLexem;
pub use morfex::Morfex;
pub use saol_lemma::SaolLemma;
pub use sentens::SentensEllerStilruta;
pub use so_base::{SoLemmaRef, SoLemmaRelation, SoLemmaRelationsTyp, SoLemmaType};
pub use so_lemma::SoLemma;
pub use superlemma::Superlemma;
pub use syntex::Syntex;
pub use uttal::Uttal;
pub use valens::Valens;
